name: artic-rampart
channels:
  - bsipos
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - "python>=3"
  - "nodejs>=12"
  - pip
  - snakemake-minimal=5.8.1
  - biopython=1.74
  - minimap2=2.17
  - seqkit_bsipos
  - samtools=1.10
  - pip:
    - binlorry==1.3.0_alpha1
    - git+https://github.com/artic-network/Porechop.git@v0.3.2pre
